### ISSUE TITLE
enhanced Readinglist

### ISSUE THREAD

**Issue by SaltatorMortis** [Spark-NF/firefox-novel-updates#1]
#### Summary
```
SUMMARY:  
- filter visible Novels:
   - older than N Days or without released chapter (div.bmhide  span#bmicon  data-url)
   - by ammount of chapters
   - by NU Tag (tr.rl_links data-tags)
   - by Name
- Enable multiple readinglists
- add support for manual readinglists

```
#### Purpose of change

enhance/use quality of live features of the NU Readinglist system

#### Proposal

use the search field to temporarily filter the current loaded Novels

> ie "#[Tag1]" will display only novels with the Tag1
> "#Bad Novel" shows the novel containing Bad Novel

give the user the ability permanently filter the Readinglist via the options
(optional add support for multiple Readinglists)

ie. define in the options that you want to scan 3 readinglists:
> - readinglist "0" with all unread Novel 
> - readinglist "4" show all the novels older than 7 Days
> - readinglist "2" show all Novel more than 25 unread chapters 

another example:
> - combine 0-4 to a single readinglist but hide all oder than 30 days
> - readinglist "5" with the tag "Tag0" or "Tag1"
> - readinglist "5" show all the novels older than 7 Days

i hope this mega suggestion isnt to convoluted and still understandable... 
Keep your work up this is a good addon

**Comment by Spark-NF** [comment]
Hello! 😄 

If I understood properly, your suggestion can be divided into three main parts:

1. Quick search directly in the "pop-up" via the search field, where instead of searching the website for novels, it would filter novels in the reading list if you prefix the search with `#`
2. Allow to show multiple/merge reading lists in the "pop-up" via the settings, instead of currently only showing the first reading list (0)
3. Allow to add rules to each "group" of reading lists for which novels to show:
    * Unread/Read (shortcut for "more/less than 1 unread chapter")
    * More/less than X unread chapters
    * Older/newer than X days

I hope I correctly understood your ideas. :sweat_smile:
If so, I'll post my comments below

-----

> use the search field to temporarily filter the current loaded Novels

I like the idea of filtering the list of shown novels, but I don't like the `#` syntax.
An alternative would be to have two search fields, but I don't like it either.

Another option would be to use the search field by default to filter novels, with a button to trigger a NU search.
What do you think? :smile:

> give the user the ability permanently filter the Readinglist via the options
> (optional add support for multiple Readinglists)

While I personnally only use one reading list, this could indeed be done by a "group" system.
The user would create "groups", in which he could add as many reading lists as he wants and as many filters as he wants. The novels contained in the group would be the sum of the novels of its reading lists, de-duplicated, and filtered.

> readinglist "4" show all the novels older than 7 Days
> combine 0-4 to a single readinglist but hide all oder than 30 days

Can you define a novel "older than X days"?
Is that the number of days since last chapter? If so, I can understand why you'd want to see "new" novels (i.e. ones still getting updates), butin which context would you want to show old novels?

**Comment by SaltatorMortis** [comment]
> Can you define a novel "older than X days"?

i didn't mean the Novel but the next Chapter 😄
Basically in this example hide/show Chapters depending on the first unread Chapter


as for how its archived after looking into the code, is pretty simple:
extract release Date from the variables from the 'latestchp' function call via your getNextChaptersByUrl 
with the same scrape you could get the 'next' and the 'latest' Chapter (onmousedown or onclick)

> `onmousedown="latestchp('697475','11924',this,'no','2017-06-13&nrid=697475')"`
 this chapter was released on 13.06.2017

taken from https://www.novelupdates.com/readinglist_getchp.php?rid=2300191&sid=11924&nrid=697475

> Another option would be to use the search field by default to filter novels, with a button to trigger a NU search.
> What do you think? 😄

sounds viable but you loose the "live" nature of your search this way my # was a simple suggestion to 'break' this only temporarily (and in Germany its right beside the Enterkey usable without any modifyer  :-P )
to speak the truth i havn't spend many thorts on this but i agree one searchfield should be enough.
maybe maintain the live nature of the Search, exept when you start the string with a Tagging symbol iE. first letter starts is [ then wait until Enter is pressed. and only then limit the search local.

**Comment by Spark-NF** [comment]
> and in Germany its right beside the Enterkey usable without any modifyer :-P

In QWERTY and AZERTY it's a pain to type however.

My main complaint about this is not that it's annoying to type another character, but that the feature would be non-obvious: only by reading the documentation or knowing about it beforehand one would be able to use it.

> `onmousedown="latestchp('697475','11924',this,'no','2017-06-13&nrid=697475')"`
> NU Tag (tr.rl_links data-tags)

On my end, `data-tags` seems to be empty and I don't have any `onmousedown`, but a `data-url` instead:

```html
<tr class="rl_links" data-sid="2072" data-title="Martial World" data-tags="" data-notes="" data-rate="" data-genreid=",8,13,5,3,14,3954,">
    <td width="5%">
        <span class="hidden">0 Martial World</span>
        <input type="checkbox" name="check" class="checkme2072 not-empty" id="chkst2072" value="1328137:2072" />
        <label onclick="" for="chkst2072" class="selchk" title="delete"></label>
    </td>
    <td width="50%" class="title_shorten">
        <a title="Martial World" href="https://www.novelupdates.com/series/martial-world/">Martial World</a>
    </td>
    <td width="20%">
        <input type="hidden" id="series2072" value="2305081" />
        <a class="chp-release" id="mystatus2305081" href="http://www.wuxiaworld.com/novel/martial-world/mw-chapter-1357" rel="nofollow">c1357</a>
    </td>
    <td width="25%">
        <a class="chp-release latest" id="mylatest2305081" href="https://www.wuxiaworld.com/novel/martial-world/mw-chapter-2128" rel="nofollow">c2128</a>
        <div class="bmhide 2305081">
            ...
        </div>
    </td>
</tr>
```

Do you have any special reading list display settings?

**Comment by SaltatorMortis** [comment]
Jep the `data-tags` are your Private Tags, to create Tags klick the Note Icon 
resulting syntax is then `data-tags=",tag1,"` or `data-tags=",tag1,tag2,"`

you are looking at the wrong site for the onmousedown.
my suggestion is to add the Date value to `novel.next` that you get from the [getNextChaptersByUrl()](https://github.com/Spark-NF/novel-updates-notifier/blob/e81cb2694d0f4b45c81c34148262621d39345e7d/src/common/NovelUpdatesClient.ts#L145-L168)

example:
visit https://www.novelupdates.com/readinglist_getchp.php?rid=2300191&sid=11924&nrid=697475
```
[].forEach.call(document.getElementsByClassName("getchp"),  atru => console.log(atru.getAttribute("onclick")))
[].forEach.call(document.getElementsByClassName("getchps"),  atru => console.log(atru.getAttribute("onmousedown")))
```
