### ISSUE TITLE
Getting more and more ERROR in the refreshing of chaptere read

### ISSUE THREAD

**Issue by LeFlemard** [Spark-NF/firefox-novel-updates#23]
Hi,
I really dunno if it's due to my poor internet, the massive internet usage during this sanitary crisis or the plugin bugging, but it keeps happening more and more frequently that the plugin isn't able to refresh for new chapters/read chapters.
This on the chrome webstore version.
Could you please check if it's a me problem or the plugin problem?
thanks for this amazing plugin anyway :3

**Comment by Spark-NF** [comment]
Hello

Indeed, I can see many errors on my version too:
> Error loading reading list TypeError: "can't access property "getElementsByTagName", xml.getElementById(...) is null"

I'll investigate and see to push a fix 👌

**Comment by Spark-NF** [comment]
After a quick investigation, it's caused by CloudFlare.

There is a "browser verification" to be done before accessing the website every few days now. For now, I suggest to simply click the "Open" button, pass the verification then it should work in the next refresh.

I'll see what can be done to detect this issue and have a more "natural" fix in the extension. Either showing an explanation with a button to click, or automatically loading the CloudFlare verification in the popup.

**Comment by SaltatorMortis** [comment]
ah thats is why it never worked...
if you use containers don't forget to login with your account in the Tab without loaded container.
that is why the other browser didn't work ether.

thy for the solution.

**Comment by Spark-NF** [comment]
I just published the 1.5.0 version, which should detect Cloudflare errors and show a better badge message and popup:

![image](https://user-images.githubusercontent.com/11507357/80012490-afc05100-84cd-11ea-9dac-27aee3bb38ad.png)

It should already be there for FF, and should arrive in Chrome once reviewed.
I wonder what happened for the NU admin to add CF challenges all of a sudden. 🤔

**Comment by Tenome** [comment]
I'm getting this error, except Open doesn't pull up a Cloudflare challenge so I can never complete it. It just pulls up the NU reading page as normal.
