### ISSUE TITLE
Is there a way to ignore a particular list?

### ISSUE THREAD

**Issue by Tenome** [Spark-NF/firefox-novel-updates#24]
I have a "Dropped" list that I don't need updates on. Would it be possible to add an "ignore" function or something so you don't get updates for it?

**Comment by Spark-NF** [comment]
Hello!

Sorry for the late answer, I missed the notification.

Yes, it's totally possible to ignore some lists, that's actually a very common thing to do since many people will have a "backlog" or "on hold" list that they don't really want notifications for.
You can do that by creating a group in the settings and selecting only the lists you want:
![image](https://user-images.githubusercontent.com/11507357/161161723-45122f8a-dfa0-499f-a115-de6b165b3a25.png)

In this screenshot, only the "reading" and "manual" lists will trigger updates.

Hope this answers your question!
