### ISSUE TITLE
Number of pending chapters not showing on badge.

### ISSUE THREAD

**Issue by Tenome** [Spark-NF/firefox-novel-updates#26]
Not sure what the issue is, but I have a fresh installation with unread chapters, and the toolbar icon no longer shows the number. I have the option selected. Does this need to be updated?

Firefox dev 127.0b9 (64-bit), Extension 1.5 (latest).

**Comment by Spark-NF** [comment]
Interesting, 1.5 is still working fine for me on Firefox 128. What color are the rows with unread chapters in the "pop-up"?

They should be yellow like this:
![image](https://github.com/Spark-NF/novel-updates-notifier/assets/11507357/553a795b-79e8-4acb-9177-dc0961c56458)

If they're grey, it could it be that the novel group in your settings is set to "ignored".

Otherwise, I guess I'll have to investigate more. Are you using multiple groups? What are your settings like? 🤔

**Comment by Tenome** [comment]
All of my rows are white, even with titles that aren't in my ignore list (first group). 

![4zooGJKHqS](https://github.com/Spark-NF/novel-updates-notifier/assets/12216081/166b7272-ffeb-443e-9325-0c2f718e7c58)


As for settings:

![3Sn57i8Mk4](https://github.com/Spark-NF/novel-updates-notifier/assets/12216081/4a1cf6c1-074d-41fa-beb6-119d685cebd5)
![jxYAQHlpHB](https://github.com/Spark-NF/novel-updates-notifier/assets/12216081/47ee4a44-ca67-4c45-8810-4b3c4a080778)

**Comment by Spark-NF** [comment]
Interesting, that would mean that it can't detect new chapters at all, rather than it's unable to count them 🤔

It can happen when the add-on can't detect chapter differences like here:
![image](https://github.com/Spark-NF/novel-updates-notifier/assets/11507357/93bfafba-aad3-4727-a277-fa20a35b045f)
Is it like this for you as well? Or are the columns totally empty?

But this kind of thing shouldn't be very common, and since you say it used to work then there must be something else. Did you maybe change the display settings of your reading list on novelupdates.com? The add-on does some manual parsing on that page, so if the layout changed it might have broke some part of the detection? 🤔 

Mine looks like this (https://www.novelupdates.com/reading-list/):
![image](https://github.com/Spark-NF/novel-updates-notifier/assets/11507357/9294ac5b-afa4-446e-a7dc-2997dc4ee720)
![image](https://github.com/Spark-NF/novel-updates-notifier/assets/11507357/e7402e48-49d9-4a06-919e-8d65c6918552)
![image](https://github.com/Spark-NF/novel-updates-notifier/assets/11507357/ef659b7b-3d89-456a-bb86-3c16f6eb89f3)

If there's a setting in there that's proven to break detection I'll gladly fix it though! 😄

**Comment by Tenome** [comment]
It suddenly started working for some reason. I think unchecking Manual Reading List fixed it (I could've swore I was on manual reading list before, though, and it worked). Thanks for the help.
